import { describe, expect, it } from "vitest";
import styles from "../src/styles.ts?raw";

describe("activity dashboard CSS", () => {
  it("styles the area dashboard structure emitted by the renderer", () => {
    [
      "--ahc-insights-width: 340px",
      "--ahc-dashboard-label-width: 250px",
      "--ahc-dashboard-row-height: 34px",
      "--ahc-dashboard-segment-height: 11px",
      "--ahc-dashboard-aggregate-height: 13px",
      "--ahc-dashboard-segment-min-width: 6px",
      "--ahc-axis-label-color: rgba(235, 242, 255, 0.92)",
      "--ahc-axis-grid-color: rgba(148, 163, 184, 0.22)",
      "--ahc-dashboard-group-header-height: 42px",
      ".ahc--density-comfortable",
      ".ahc--density-compact",
      ".ahc--density-ultra-compact",
      ".ahc--fixed-overlay",
      ".ahc__hero",
      ".ahc__toolbar",
      ".ahc__summary-strip",
      ".ahc__body",
      ".ahc__main",
      ".ahc__insights-panel",
      ".ahc-dashboard",
      ".ahc-dashboard__header",
      ".ahc-dashboard__density",
      ".ahc-dashboard__axis",
      ".ahc-dashboard__timeline",
      ".ahc-dashboard__scroll",
      ".ahc-dashboard__lanes",
      ".ahc-area-lane",
      ".ahc-area-lane--active",
      ".ahc-area-lane--inactive",
      ".ahc-area-lane__header",
      ".ahc-area-lane__title",
      ".ahc-area-lane__meta",
      ".ahc-area-lane__inventory-trigger",
      ".ahc-area-lane__aggregate",
      ".ahc-area-lane__rows",
      ".ahc-lane-row",
      ".ahc-lane-row__label",
      ".ahc-lane-row__name",
      ".ahc-lane-row__duration",
      ".ahc-lane-row__plot",
      ".ahc-inventory-drawer",
      ".ahc-inventory-drawer__items",
      ".ahc-timegrid",
      ".ahc-timegrid__grid",
      ".ahc-timegrid__segments",
      ".ahc-timegrid__line--major",
      ".ahc-timegrid__line--minor",
      ".ahc-timegrid__now-label",
      ".ahc-dashboard-group",
      ".ahc-dashboard-group__header",
      ".ahc-dashboard-group__aggregate",
      ".ahc-dashboard-group__rows",
      ".ahc-dashboard-row",
      ".ahc-dashboard-row__label",
      ".ahc-dashboard-row__label-copy",
      ".ahc-dashboard-row__state",
      ".ahc-dashboard-row__plot",
      ".ahc-dashboard-row__meta",
      ".ahc-dashboard-segment",
      ".ahc-dashboard-segment--cooling",
      ".ahc-dashboard-segment--heating",
      ".ahc-dashboard-segment--playing",
      ".ahc-area-inventory",
      ".ahc-area-card__inventory-preview",
      ".ahc-inventory-chip",
      ".ahc-inventory-chip__state",
      ".ahc-area-card__title",
      ".ahc-area-card__aggregate",
      ".ahc-area-card__content",
      ".ahc-area-card__activity",
      ".ahc-dashboard-row__inline-meta",
      ".ahc-inventory-chip__status",
      '[data-state-tone="active"]',
      '[data-state-tone="unavailable"]',
      "block-size: 46px",
      "block-size: max(5px, calc(var(--intensity, 0) * 28px))",
    ].forEach((selector) => {
      expect(styles).toContain(selector);
    });
  });
});
