import { describe, expect, it } from "vitest";
import styles from "../src/styles.ts?raw";

const emittedDashboardClasses = [
  "ahc-dashboard",
  "ahc-dashboard-empty",
  "ahc-dashboard__header",
  "ahc-dashboard__title-block",
  "ahc-dashboard__range-pill",
  "ahc-dashboard__density",
  "ahc-dashboard__density-bars",
  "ahc-dashboard-density-bucket",
  "ahc-dashboard-density-fill",
  "ahc-dashboard__density-labels",
  "ahc-dashboard__timeline",
  "ahc-dashboard__axis",
  "ahc-dashboard__axis-labels",
  "ahc-dashboard__tick",
  "ahc-dashboard__axis-label",
  "ahc-dashboard__scroll",
  "ahc-dashboard__hidden-note",
  "ahc-dashboard__notice",
  "ahc-timegrid",
  "ahc-timegrid--density",
  "ahc-timegrid--aggregate",
  "ahc-timegrid--row",
  "ahc-timegrid__grid",
  "ahc-timegrid__segments",
  "ahc-timegrid__line",
  "ahc-timegrid__line--major",
  "ahc-timegrid__line--minor",
  "ahc-timegrid__now",
  "ahc-timegrid__now--label",
  "ahc-timegrid__now-label",
  "ahc-area-card",
  "ahc-area-card__header",
  "ahc-area-card__title",
  "ahc-area-card__title-copy",
  "ahc-area-card__actions",
  "ahc-area-card__meta",
  "ahc-area-card__inventory-button",
  "ahc-area-card__aggregate",
  "ahc-area-card__content",
  "ahc-area-card__activity",
  "ahc-area-card__quiet",
  "ahc-dashboard-group",
  "ahc-dashboard-group__header",
  "ahc-dashboard-group__title",
  "ahc-dashboard-group__meta",
  "ahc-dashboard-group__aggregate",
  "ahc-dashboard-group__body",
  "ahc-dashboard-group__rows",
  "ahc-dashboard-group__more",
  "ahc-dashboard-row",
  "ahc-dashboard-row__label",
  "ahc-dashboard-row__inline-meta",
  "ahc-dashboard-row__plot",
  "ahc-dashboard-row__meta",
  "ahc-dashboard-segment",
  "ahc-dashboard-segment--row",
  "ahc-dashboard-segment--aggregate",
  "ahc-dashboard-segment--min",
  "ahc-dashboard-icon",
  "ahc-area-inventory",
  "ahc-area-inventory__header",
  "ahc-area-inventory__groups",
  "ahc-area-inventory__domain",
  "ahc-area-inventory__domain-title",
  "ahc-area-inventory__chips",
  "ahc-area-inventory__more",
  "ahc-inventory-chip",
  "ahc-inventory-chip__copy",
  "ahc-inventory-chip__status",
] as const;

describe("dashboard CSS contract", () => {
  it("styles every dashboard class emitted by the activity dashboard renderer", () => {
    for (const className of emittedDashboardClasses) {
      expect(styles, `Missing selector for .${className}`).toContain(
        `.${className}`,
      );
    }
  });
});
